name: Check links on .md

on:
  workflow_dispatch:
  push:
    paths:
      - "**.md"
  pull_request:
    paths:
      - "**.md"

jobs:
  check-link:
    runs-on: ubuntu-22.04

    steps:
      - name: Project checkout
        uses: actions/checkout@v5
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: ".github/mlc_config.json"
